homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
  user: '!secret user'
  password: '!secret password'
serial:
  port: /dev/ttyACM0
  disable_led: true
devices: devices.yaml
